.TH ICARO "1" "September 2016" "icaro 1.0.6" "User Commands"
.SH NAME
icaro \- Robótica educativa con software y hardware libre
.SH SYNOPSIS
.B icaro

.SH DESCRIPTION
Entorno de programación para robótica educativa con software y hardware libre
.LP
.SH AUTHORS
.B icaro
was written by Valentin Basel <http://roboticaro.org/>.
.P
This manual page was written to satisfy lintian by 
Fernando Toledo <ragnarok@docksud.com.ar> for the Huayra 
project (but may be used by others).
